### ISSUE TITLE
现在是不是没法使用弹幕抓取功能了

### ISSUE THREAD

**Issue by joechenrh** [davidkingzyb/pccold#15]
无法连接openbarrage.douyutv.com

**Comment by davidkingzyb** [comment]
可以用，`$ pccolddanmu`
需配置
```
#弹幕配置
username="visitor9986987" #弹幕登陆名
uid="1167614891" #弹幕 user ID
```

**Comment by joechenrh** [comment]
好的，感谢

**Comment by joechenrh** [comment]
不好意思再问一下，这个弹幕抓取是不是不能抓到**所有**弹幕（所有是相对于网页版）

**Comment by davidkingzyb** [comment]
和网页一样的、

**Comment by joechenrh** [comment]
> 和网页一样的、
![捕获](https://user-images.githubusercontent.com/18008525/71869842-87932900-314e-11ea-8724-a1798eca4c70.JPG)
两个终端，收到的弹幕可能会不一样

**Comment by davidkingzyb** [comment]
你用的是这个么？

**Comment by joechenrh** [comment]
> 你用的是这个么？

对的，就是改了一下输出格式和输出内容，去掉了除`chatmsg`类型以外消息的处理

**Comment by joechenrh** [comment]
> > 你用的是这个么？
> 
> 对的，就是改了一下输出格式和输出内容，去掉了除`chatmsg`类型以外消息的处理

我在想是不是`WebSocketApp`的问题，我还是想办法把chrome里收到的数据导出来对比看看吧😗

**Comment by joechenrh** [comment]
看了一下收到的数据，一次收到的数据可能包含若干条信息（可能是不同类型，也可能是两条弹幕），所以还得想办法先对原数据split才行。

**Comment by davidkingzyb** [comment]
> 看了一下Python收到的数据，一次收到的数据可能包含若干条信息（可能是不同类型，也可能是两条弹幕），所以还得想办法先对原数据split才行。

好像是的，之前没有注意到这个问题
![1](https://user-images.githubusercontent.com/6694635/71882980-693e2500-3170-11ea-83c2-4e5bcbf5cce6.png)

**Comment by davidkingzyb** [comment]
我有空重新实现下pystt，感谢提问

**Comment by joechenrh** [comment]
现在暂时靠找`type@=`来分割，应该不会有其他的键值对里出现这个关键词吧
```python
def split(message): 
    pos = [ ] 
    type_pos = message.find(b'type@=')
    while type_pos != -1:
        pos.append(type_pos)
        type_pos = message.find(b'type@=', type_pos + 1)
    
    pos.append(len(message) + 12)
    
    messages = [ ]
    for i in range(len(pos) - 1):
        messages.append(message[pos[i]: pos[i + 1] - 12 - 1])
    
    return messages
```

**Comment by davidkingzyb** [comment]
merge #16 ，更新在版本v0.29 。thx PR
