### ISSUE TITLE
请问这个提示是什么

### ISSUE THREAD

**Issue by zzzop** [davidkingzyb/pccold#4]
`# python manual.py
Block request http://www.douyu.com/lapi/live/getPlay/(roomid)
Enter getPlay request query:`

**Comment by davidkingzyb** [comment]
这个是在streamlink插件用不了的时候用的，在chrome控制台network找到这个请求右键block request，刷新将这个请求url作为input输入

**Comment by zzzop** [comment]
> 这个是在streamlink插件用不了的时候用的，在chrome控制台network找到这个请求右键block request，刷新将这个请求url作为input输入

非常感谢

**Comment by davidkingzyb** [comment]
一般用法的话，设置好conf.py
然后 $ nohup python3 pccold.py &
就可以了

**Comment by zzzop** [comment]
> 一般用法的话，设置好conf.py
> 然后 $ nohup python3 pccold.py &
> 就可以了

新手上路，配置添加了，不过Python好像出了什么问题。。我研究一下。默认的是冷冷的直播，才发现
