### ISSUE TITLE
运行时间长被断开后无法重新连接

### ISSUE THREAD

**Issue by jiangnoyes** [davidkingzyb/pccold#5]
运行录制了2小时的视频，自动断开被提示：‘远程主机强迫关闭了一个现有的连接’，
手动再次运行会被提示
[cli][info] Found matching plugin douyutv for URL http://www.douyutv.com/988
[plugin.douyutv][info] Stream currently unavailable.
error: No playable streams found on this URL: http://www.douyutv.com/988
请问：这个是什么原因导致的？能修复或者避免吗？是不是IP被封了？

**Comment by jiangnoyes** [comment]
五六个小时后重新运行，可以继续下载了

**Comment by davidkingzyb** [comment]
应该是斗鱼有限制录像的长度。可以设置conf里
is_cut=True #是否分段
how_long=60*30 #录像分段长度(秒)
这两个值
定时kill掉streamlink进程
