### ISSUE TITLE
指定的直播间找不到设定的录像质量

### ISSUE THREAD

**Issue by jiangnoyes** [davidkingzyb/pccold#6]
error: The specified stream(s) 'medium' could not be found.
       Available streams: source_http, source (worst, best)
有什么办法能获取到所录制的直播间当前支持的录像质量吗？
如果有的话，我就可以根据获取到的值来做个判断取值。

**Comment by jiangnoyes** [comment]
不好意思，伸手伸惯了。去看了下官方文档和其他帖子。获取录像质量列表内容如下：
import subprocess
out_bytes = subprocess.check_output('streamlink http://www.douyutv.com/4334531',shell=True)
out_text = out_bytes.decode('utf-8')
print(out_text)

[cli][info] Found matching plugin douyutv for URL http://www.douyutv.com/4334531
Available streams: source_http, low (worst), medium, source (best)

**Comment by davidkingzyb** [comment]
或者使用streamlink的api
import streamlink
streams = streamlink.streams("url

在conf里可以设置录像质量，斗鱼一般低质量的会晚一点才能获取到，获取不到的时候会尝试30秒后获取
