### ISSUE TITLE
run download.py error

### ISSUE THREAD

**Issue by hurun** [davidkingzyb/pccold#7]
D:\>cd D:\python\pccold-master

D:\python\pccold-master>python videodownload.py
Traceback (most recent call last):
  File "videodownload.py", line 9, in <module>
    from tools import read,doBypy,saveStream,ReturnCodeObserverThread,SleepKillerThread
ImportError: cannot import name 'doBypy'

**Comment by davidkingzyb** [comment]
sorry function `doBypy` move into bypyrm.py
try `from bypyrm import doBypy`

**Comment by davidkingzyb** [comment]
https://github.com/davidkingzyb/pccold/commit/2656bd1d9e31518177c7ebe659cc70e752cd47b7

**Comment by hurun** [comment]
无法导入doBypy修复了， 现在又出现新问题

D:\python\pccold-master>python videodownload.py
videodownload main
系统找不到指定的路径。

**Comment by davidkingzyb** [comment]
有配置videolist和download文件夹吗？

**Comment by hurun** [comment]
这是conf配置文件，不知道对不对
download_path="./download" #录像保存路径
videolist_path='videolist.md' #批量下载斗鱼视频列表

试过相对路径与绝对路径，报相同错误
