### ISSUE TITLE
请教一下Windows平台如何配置conf，让脚本正常运行

### ISSUE THREAD

**Issue by hurun** [davidkingzyb/pccold#8]
只需要录像及下载视频，下面是参考readme设置的conf，cmd运行pccold.py一直显示提示符，download文件夹没有文件产生

room_id="cold" #斗鱼房间ID
room_num=20360 #斗鱼房间数字ID
stream_type='medium' #录像质量 source|medium|low
is_cut=True #是否分段
how_long=2*30 #录像分段长度(秒)
is_bypy=True #是否使用bypy上传百度云
is_bypy_rm=False #上传百度云后删除
download_path="./download" #录像保存路径
videolist_path='videolist.md' #批量下载斗鱼视频列表

#api
room_api='https://www.douyu.com/betard/' 
room_url="http://www.douyutv.com/"

#邮件配置
my_email="recv@xx.com"
mail_sender='send@xx.com'
mail_passwd='xxx'
mail_host='xxx'
mail_port=25 #exmail.qq 465 or 25
pccold_contact="\n\npccold by DKZ \n---------------------\ngithub:https://github.com/davidkingzyb/pccold\ncontact:davidkingzyb@qq.com  @__DKZ__\naboutme:https://davidkingzyb.tech\n"

#手动录像脚本路径
manual_tmpl_path='./douyutv.py'
now_tmpl_path='xxx'
douyutv_plug_path='/Library/Python/2.7/site-packages/streamlink/plugins/douyutv.py'

**Comment by davidkingzyb** [comment]
这个脚本设计的作用是在服务器上轮询，如果主播开播自动调用streamlink下载，不开播的时候是没有下载的。如果是只需要下载录像可以直接使用streamlink下载，参见streamlink的windows配置https://streamlink.github.io/install.html#windows-binaries。暂时没有测试批量下载脚本能否在windows上使用，不过如果streamlink配置好的化应该是可以使用的。

**Comment by Jaqen00** [comment]
你需要用ide运行程序，找出不适配的错误，修改代码
比如代码中结束进程的命令windows下是没有的，需要修改

**Comment by Jaqen00** [comment]
给作者说声感谢，给了不少思路😃
有个问题想问一下，在检测主播是否上线的时候，一次轮询完为什么要重开一个线程继续轮询，这样做有什么好处，用个循环不断监测不也可以么

**Comment by davidkingzyb** [comment]
@Jaqen00 谢谢，使用线程主要是因为视频分段的时候不希望两段之间的直播没有录到，所以要在上个线程结束前新起线程录制，把这个和轮询做在了一起。

关于windows平台上的使用问题，这个项目本来设计的是在服务器上24小时跑的。如果有在windows上使用的需求可以考虑之后用pyinstaller打一个windows可用的exe出来，不过目前没有这个开发计划。建议自行fork一个项目修改或使用虚拟机。

**Comment by Jaqen00** [comment]
streamlink斗鱼插件挂了，有替代方案嘛😂

**Comment by davidkingzyb** [comment]
@Jaqen00 昨天晚上好像还正常
你是用的pip安装的最新的版本吗？
![streamlink](https://user-images.githubusercontent.com/6694635/53399096-38d11a80-39e6-11e9-8734-edeec1e5040c.png)
把streamlink删掉后重装下试试
之前的版本可以暂时使用手动脚本

这个windows问题的单我先关了

**Comment by Jaqen00** [comment]
今天早上挂的，是streamlink的问题

**Comment by davidkingzyb** [comment]
好像是的，之前的接口不行了，手动脚本也用不了。
