### ISSUE TITLE
鉴权问题

### ISSUE THREAD

**Issue by zzjzz9266a** [davidkingzyb/pccold#9]
`error: Unable to open URL: https://capi.douyucdn.cn/api/v1/room/1126960?aid=wp&cdn=ws&client_sys=wp&time=1551323634&auth=d9228faf7e82a2878d6fdbace7d01f15 (401 Client Error: Unauthorized for url: https://capi.douyucdn.cn/api/v1/room/1126960?aid=wp&cdn=ws&client_sys=wp&time=1551323634&auth=d9228faf7e82a2878d6fdbace7d01f15)`
貌似斗鱼的api需要注册账号然后才给权限？

**Comment by davidkingzyb** [comment]
20190226斗鱼这个API失效了，导致streamlink的斗鱼插件不可用。请关注斗鱼插件的更新https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/douyutv.py
这个项目也会在新的API出来后同步更新

**Comment by zzjzz9266a** [comment]
好的，谢谢~~

**Comment by Jaqen00** [comment]
https://github.com/zhangn1985/ykdl
这个是可以用的

**Comment by Jaqen00** [comment]
https://github.com/zhangn1985/ykdl/issues/378

**Comment by davidkingzyb** [comment]
这个问题好像一直没有好的解决方案，目前的方案都要使用js。
我贴一个我在使用的临时方案，使用puppeteer操作浏览器获取视频流。
供大家参考https://github.com/davidkingzyb/pccold_puppeteer

**Comment by qchenac** [comment]
能问一下这个puppeteer在mac os下应该怎么用吗？

**Comment by davidkingzyb** [comment]
和linux一样的，装nodejs环境，把douyutv.py插件拷到livestreamer对应目录下，在puppter目录下运行pccold

**Comment by xiaoyao9184** [comment]
@davidkingzyb 请问 https://github.com/davidkingzyb/pccold_puppeteer/blob/89a7cb1fe996e3021b90883b8e1eefb41fe0bbd9/index.js#L20-L22 这个参数替换是干什么用的？

**Comment by davidkingzyb** [comment]
录像质量
